### PR TITLE
cohere API

### PR DESCRIPTION
**Pull request by m5kro**
This adds the cohere API as an option instead of openai. There's only RPG mv/mz right now and it needs a lot more work to be as good as chatgpt.

A few things to note:
The prompt definitely needs some fine-tuning as some/lots of lines are not being translated and it also needs to bypass the [usage guidelines](https://docs.cohere.com/docs/usage-guidelines).

The free trial API has a limit of 10-20 requests per minute, there is a variable in the Python file for the delay between requests.

I only tried the command-r model, the commad-r-plus model may perform better. 

Here are the test json files I used:
[data-ja.zip](https://pixeldrain.com/u/Aer6Hrww)
[test-translate.zip](https://pixeldrain.com/u/NF58QPqa) <--output

Also here's an example response from the API:
`text='Sir Isaac Newton was born on December 25, 1642, in Woolsthorpe, Lincolnshire, England.' generation_id='681a5777-0947-4829-a7d7-f3d2aededc3d' citations=None documents=None is_search_required=None search_queries=None search_results=None finish_reason='COMPLETE' tool_calls=None chat_history=[ChatMessage(role='USER', message='Who discovered gravity?'), ChatMessage(role='SYSTEM', message='The man who is widely credited with discovering gravity is Sir Isaac Newton'), ChatMessage(role='USER', message='when was he born'), ChatMessage(role='CHATBOT', message='Sir Isaac Newton was born on December 25, 1642, in Woolsthorpe, Lincolnshire, England.')] meta=ApiMeta(api_version=ApiMetaApiVersion(version='1', is_deprecated=None, is_experimental=None), billed_units=ApiMetaBilledUnits(input_tokens=21, output_tokens=27, search_units=None, classifications=None), tokens=ApiMetaTokens(input_tokens=93, output_tokens=27), warnings=None) response_id='3201dc29-bf56-4b0f-93ce-9ec26ba35598'`

### CODE REVIEW

**Comment by dazedanon** [comment]
Hmm ideally I'd rather not have different modules for each translation engine that gets implemented since it will make maintaining them hell. Was there a challenge in integrating them into the current modules?

**Comment by m5kro** [comment]
It's acually really easy to implement the API since it is similar to the openai API. You can see which lines I changed [here](https://github.com/dazedanon/DazedMTLTool/pull/19/commits/ba126301788aa3038282993ae0a6f5a4c4e46780). The only reason I made it a different module was because I didn't want to accidentally break anything with the openai stuff.

**Comment by m5kro** [comment]
Nvm fixed it.

**Comment by m5kro** [comment]
gonna close this for now as there seems to be no interest

**Comment by dazedanon** [comment]
> gonna close this for now as there seems to be no interest

Ah yes sorry slipped my mind. I don't plan on using this so lets leave it closed.

**Pull request closed without merging**
